README.md, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, src/DocumentView/DocumentView.js
Adds an `initialPageNumber` prop to `DocumentView`. If an initial page number is provided the document's current page number will be set to the specified value as soon as it is loaded.
=> initialPageNumber prop

README.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, example/App.js, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, src/DocumentView/DocumentView.js
- onAnnotationChanged
- exportAnnotations(options)
=> Adds annotation changed event

ios/RNTPTDocumentView.m
Fixes an issue with the toolbar staying hidden after exiting search mode.
=> Allow showing (hidden) controls even when auto-hide is off.

android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.m
back to pan tool before flatten to ensure latest changes are saved
=> [Fix] issue where currently typing form fields are not saved when flattening

README.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, src/Config/Config.js, src/DocumentView/DocumentView.js
This function allows setting a form field flag value on a list of fields (as specified by name). In our case we want to be able to programmatically set/clear the readonly flag on a number of form fields.
I'm not well versed on native module development for RN so any feedback is welcome.
implements #48
=> Add setFlagForFields function

android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
don't fix system window for all views
=> Fix issue where system status bar is shown when using the view as a sub component

README.md, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, src/DocumentView/DocumentView.js
=> New padStatusBar prop for android to fix status bar overlap

README.md, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/DocumentViewController/RNTPTCollaborationDocumentViewController.m, ios/DocumentViewController/RNTPTDocumentViewController.m, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, src/DocumentView/DocumentView.js
prop:
- selectAnnotationAfterCreation
- overrideAnnotationMenuBehavior
event:
- onAnnotationMenuPress
=> New props and event related to annotation and menu

README.md, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/DocumentViewController/RNTPTCollaborationDocumentViewController.m, ios/DocumentViewController/RNTPTDocumentViewController.m, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, src/DocumentView/DocumentView.js
Also adds the "pageNumber" field to the `onAnnotationMenuPressed`'s annotations
=> Add onAnnotationsSelected prop

README.md, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/DocumentViewController/RNTPTCollaborationDocumentViewController.m, ios/DocumentViewController/RNTPTDocumentViewController.h, ios/DocumentViewController/RNTPTDocumentViewController.m, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, src/Config/Config.js, src/DocumentView/DocumentView.js
new:
longPressMenuItems: PropTypes.array,
overrideLongPressMenuBehavior: PropTypes.array,
onLongPressMenuPress: PropTypes.func,
hideAnnotationMenu: PropTypes.array,
=> Hide annotation menu prop and Long press menu props

ios/RNTPTDocumentView.m
- measurement tools
- callout tool
- and image stamp tool
- Also add support for disabling image stamp tool
=> [iOS] Add support to programmatically activate some missing tools

README.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, src/DocumentView/DocumentView.js
remove old method that was not very useful
=> New handleBackButton method (android only)

README.md, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, package.json, src/DocumentView/DocumentView.js
For allowing remote saving of signature appearance via XFDF
=> signSignatureFieldsWithStamps prop

ios/RNTPTDocumentView.m, package.json
=> Hide all annotation menu items when list is empty

ios/RNTPTDocumentView.m
Missing button when starting in regular horizontal size class
=> Fix leadingNavButton (iOS)

android/build.gradle, package.json
=> [droid] Fix issue where favorites list is showing hidden toolbar items

README.md, android/build.gradle, android/src/main/java/com/pdftron/reactnative/utils/Constants.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, package.json, src/DocumentView/DocumentView.js
Implement Tool-changed event;
Updated some missing constants (or marked as TODO)
=> Tool changed event

README.md, android/build.gradle, android/src/main/java/com/pdftron/reactnative/modules/RNPdftronModule.java, package.json
new api to clear rubber stamp cache (android only)
=> [droid] adds clearRubberStampCache API

package.json, scripts/README.md, scripts/fileCopy.py
Added automation Python script (file copying) for convenience purpose
=> Added automation script for react native

API.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, package.json, src/DocumentView/DocumentView.js
Functions:
getAnnotationAtPoint
getAnnotationsAtLine
getAnnotationsOnPage
=> get annotation(s)

API.md, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, package.json, src/DocumentView/DocumentView.js
add showQuickNavigationButton
https://support.pdftron.com/a/tickets/22074
- add showQuickNavigationButton property to show or hide quick navigation buttons
=> [Android] add showQuickNavigationButton

API.md, android/src/main/java/com/pdftron/reactnative/utils/Constants.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, example/App.js, package.json, src/Config/Config.js
Add ITEM-ID_COLORMODE to hide colors
https://support.pdftron.com/a/tickets/22148
- add a new enum item for color mode
=> [Android] Add ITEM-ID_COLORMODE to hide colors

API.md, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, package.json
(Requires a recent stable nightly build of the native iOS SDK)
=> Implement hideViewModeItems functionality on iOS

API.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, package.json, src/DocumentView/DocumentView.js
Exposed an API that retrieves an annotation's customData property.
=> getCustomDataForAnnotation

API.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, package.json, src/DocumentView/DocumentView.js
getPropertiesForAnnotation retrieves an annotation's properties, excluding customData.
=> getPropertiesForAnnotation

README.md, package.json
Updated this section to include instructions on how to use local files
=> Update Usage section of  README.md

android/src/main/java/com/pdftron/reactnative/utils/Constants.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, src/Config/Config.js
Ticket: https://support.pdftron.com/a/tickets/23262
- Added new constant BUTTON_VIEW_LAYERS_TOOLBAR to android
- Updated DocumentView to handle BUTTON_VIEW_LAYERS_TOOLBAR
- Added showViewLayersToolbarButton to Config.js
=> [Support] Android show/hide view layers button

package.json
updated version number: 2.0.3-beta.122
=> updated version number : 2.0.3-beta.122

API.md, android/build.gradle, android/src/main/java/com/pdftron/reactnative/utils/Constants.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, package.json, src/Config/Config.js, src/DocumentView/DocumentView.js
- Added eraserType property 
- Added setEraserType function to DocumentView.java
- Added eraser Type constants 
- Updated version 
- Updated API.md
=> [Support] Android default eraser type

API.md
update annotationsListEditingEnabled name in docs to match code
=> update annotationsListEditingEnabled name in docs to match code

API.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/utils/Constants.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, package.json, src/DocumentView/DocumentView.js
Exposed APIs to:
* Detect changes in the undo/redo stack's state
* Tell whether an undo/a redo operation can be performed on the current document
=> [Support] Undo/Redo State APIs

API.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/nativeviews/RNPdfViewCtrlTabFragment.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, package.json, src/DocumentView/DocumentView.js
Exposed `showGoToPageView` method for iOS and Android. 
When called, a go-to page dialog is opened.
=> [support] Expose showGoToPageView

API.md, package.json, src/DocumentView/DocumentView.js
- Resolved inconsistency between method names in `API.md` and `DocumentView.js`.
- Added a missing parameter for `getSelection` documentation.
=> Edit API method documentation

API.md, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, package.json, src/DocumentView/DocumentView.js
Exposed an API that allows users to determine if the scrollbars will be shown in the viewer
=> (Support) hideScrollbars

API.md, ios/RNTPTDocumentView.m, package.json
Updated `setDrawAnnotations` method (hides/shows all annots).
=> [support] Update setDrawAnnotations

API.md, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, package.json, src/DocumentView/DocumentView.js
Implemented prop to hide reply review state in the collaboration viewer.
=> Hide Reply Review State

API.md, android/build.gradle, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, src/DocumentView/DocumentView.js
Exposed APIs that excluded specified annotation types from the annotation list
=> (Support) Excluded Annotation Types

API.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, package.json, src/DocumentView/DocumentView.js
Exposed `toggleReflow` which allows the user to programmatically enter and exit reflow mode.
=> Expose toggleReflow

API.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, package.json, src/DocumentView/DocumentView.js
Exposed `isReflowMode` for iOS and Android.
`isReflowMode` method returns whether the viewer is currently in reflow mode.
=> Expose isReflowMode

API.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, package.json, src/DocumentView/DocumentView.js
Exposed an API that will open the tab switcher in a multi-tab environment for the user.
=> Open Tab Switcher 

API.md, package.json
Updated the example for `onFormFieldValueChanged` documentation. Also fixed a little capitalisation typo.
=> onFormFieldValueChanged example fix

API.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, package.json, src/DocumentView/DocumentView.js
Removed setUrlExtraction() from the library as it was a method call that would not work.
=> Remove setUrlExtraction()

API.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, package.json, src/DocumentView/DocumentView.js
Exposed `openSearch` method.
This method displays a search bar that allows the user to enter and search text within a document.
=> openSearch

API.md, android/src/main/java/com/pdftron/reactnative/utils/Constants.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/DocumentViewController/RNTPTCollaborationDocumentController.m, ios/DocumentViewController/RNTPTCollaborationDocumentViewController.m, ios/DocumentViewController/RNTPTDocumentController.m, ios/DocumentViewController/RNTPTDocumentViewController.h, ios/DocumentViewController/RNTPTDocumentViewController.m, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, package.json, src/DocumentView/DocumentView.js
Exposed `onPageMoved` event listener. 
This function is called when a page has been moved in the document.
=> Expose onPageMoved

.github/workflows/jsBuilder.yml, example/package.json
Add a `prestart` script to `example/package.json` and use this PR to test a new build process.
=> (test) Add a prestart script

API.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, package.json, src/DocumentView/DocumentView.js
Exposed `getSavedSignatures`, `getSavedSignatureFolder` for iOS and Android.
=> (Support) getSavedSignatures, getSavedSignatureFolder

API.md, android/src/main/java/com/pdftron/reactnative/utils/Constants.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, package.json, src/DocumentView/DocumentView.js
Exposed `onTabChanged` event for Android and iOS.
=> (Support) Expose onTabChanged

API.md
I realised that I missed some props in my original PR (See PR #363). This update corrects that.
=> Updated prop typings in the API docs

android/build.gradle, package.json
Updated Android version to snapshot 9.1.1-beta02
Updated version to 2.0.3-beta.184
=> [Support] Updated Android version to snapshot 9.1.1-beta02

API.md, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, package.json, src/Config/Config.js
Exposed `defaultEraserType` prop for iOS.
=> (iOS) defaultEraserType

API.md, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, package.json
Added prop to control the visibility of the quick navigation button on iOS
=> (Support) (iOS) Quick Navigation Button

ios/RNTPTDocumentView.m, package.json
Signed-off-by: James Borthwick <jborthwick@pdftron.com>
=> Fix mem leak by using weak proxy

android/build.gradle, package.json
Update to version `9.1.2-beta04`
=> [Android] Update Android version to latest snapshot

API.md, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, lib/src/DocumentView/DocumentView.js, package.json, src/DocumentView/DocumentView.tsx
Created prop to set the overflow menu button icon.
=> (Support) Set overflow menu button icon

API.md, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, package.json
Implemented the iOS version of the `reflowOrientation` prop.
Updated the default value stated within the API documentation.
=> (iOS) reflowOrientation 

API.md, android/src/main/java/com/pdftron/reactnative/modules/RNPdftronModule.java, index.ts, ios/RNPdftron.m, package.json
Exposed API on `RNPdftron` to convert Office files to PDF.
=> (Support) PDF from Office converter

API.md, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, lib/src/DocumentView/DocumentView.js, package.json, src/DocumentView/DocumentView.tsx
Exposes `storeNewSignature` for iOS.
=> (iOS) storeNewSignature

API.md, android/build.gradle, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, lib/src/DocumentView/DocumentView.js, package.json, src/DocumentView/DocumentView.tsx
Add `documentExtension` when opening doc.
=> Document extension

ios/RNTPTDocumentView.m, package.json
Added support on iOS to disable smart pen tool
=> (iOS) Disable smart pen

android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, package.json
Commit the current tool before saving the document.
=> (Support, Android) commit tool when saveDocument is called

package.json
updated to version 3.0.2-beta.33
=> [Android/26970] updated to version 3.0.2-beta.33

android/build.gradle, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, package.json
Switch back to native fix for https://github.com/PDFTron/pdftron-react-native/pull/446
=> [Android] Switch back to native fix

android/build.gradle, android/src/main/java/com/pdftron/reactnative/nativeviews/RNPdfViewCtrlTabHostFragment.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, package.json
Fixes https://github.com/PDFTron/pdftron-react-native/issues/447
=> [Support-27411] Handle situation where view is attached to nested fragment

ios/RNTPTDocumentView.m, package.json
=> Reverse iOS top app nav bar right bar ordering

android/build.gradle, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, package.json
Updated Android SDK version to 9.1.3-beta14
Changed setTextSearchListener to addTextSearchListener to resolve the text search highlight issue
=> [Android] Text Search Highlight Fix

API.md, lib/src/DocumentView/DocumentView.js, src/DocumentView/DocumentView.tsx
onLoadComplete callback Monday
=> onLoadComplete callback

API.md, README.md, example/ios/Podfile, package.json, scripts/newPodspecMessage.py
There is a new podspec to use when integrating the PDFTron React Native Wrapper for iOS:
https://pdftron.com/downloads/ios/react-native/latest.podspec
=> New iOS podspec

.github/workflows/npm_publish.yml, package.json, scripts/postpublish.sh, scripts/prepare.sh
* Added license field
* Added pre and post script so that package name is consistent with GitHub but different for npm
=> added licensing and other changes

API.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, lib/src/DocumentView/DocumentView.js, package.json, src/DocumentView/DocumentView.tsx
closes https://github.com/PDFTron/pdftron-react-native/issues/502
=> [Android] Ability to choose from FDFUpdate and FDFMerge

android/build.gradle, package.json
Updated PDFTron SDK version for Android
=> Android PDFTron SDK update 9.2.1-beta04

android/build.gradle, package.json
Updated PDFTron SDK version for Android
=> Update PDFTron Android SDK to 9.2.1-beta05

API.md, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, package.json
closes https://github.com/PDFTron/pdftron-react-native/issues/513
=> [Android] Fix importAnnotations when collab manager exists

android/build.gradle, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, package.json
closes https://github.com/PDFTron/pdftron-react-native/issues/518
=> Update to Android 9.2.1-beta08

API.md, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, lib/src/DocumentView/DocumentView.js, src/DocumentView/DocumentView.tsx
=> adding fitPolicy Prop

API.md, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, lib/src/DocumentView/DocumentView.js, src/DocumentView/DocumentView.tsx
this is an empty prop i.e it doesn't do anything.
The reasoning for making it empty is because we have a document prop that is already required
=> adding source prop

android/build.gradle, package.json
=> [Android] Typed signature colour fix

android/src/main/java/com/pdftron/reactnative/utils/Constants.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/DocumentViewController/RNTPTDocumentViewController.h, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, lib/src/DocumentView/DocumentView.js, package.json, src/DocumentView/DocumentView.tsx
https://linear.app/pdftron/issue/CPM-1/event-add-api-to-detect-changes-in-number-of-signatures
=> API for changes in number of saved signatures

API.md, package.json
https://linear.app/pdftron/issue/CPM-9/add-documentation-for-onsavedsignatureschanged
=> Updated API.md to include onSavedSignaturesChanged

index.ts, package.json
https://linear.app/pdftron/issue/CPM-8/make-optional-argument-required-in-api-to-convert-office-files-to-pdf
=> Make options parameter in pdfFromOffice required

API.md, android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java, android/src/main/java/com/pdftron/reactnative/modules/RNPdftronModule.java, android/src/main/java/com/pdftron/reactnative/utils/ReactUtils.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, index.ts, ios/RNPdftron.h, ios/RNPdftron.m, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.h, ios/RNTPTDocumentViewManager.m, ios/RNTPTDocumentViewModule.m, lib/src/DocumentView/DocumentView.js, package.json, src/DocumentView/DocumentView.tsx
https://linear.app/pdftron/issue/CPM-5/[support-30542]-nitrolabs-export-signature-to-png-transparent
=> Export as transparent PNG

android/build.gradle, package.json
Update Android to  stable 9.2.3-beta06
=> [Android] Update to stable 9.2.3-beta06

API.md, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, package.json
https://linear.app/pdftron/issue/CPM-10/[support-29750]-support-for-maxsignaturecount-on-ios
=> Max signature count iOS CPM-10

android/src/main/java/com/pdftron/reactnative/modules/RNPdftronModule.java, example/App.js, package.json
Adds recent file manager that was missed in the original commit
=> [Support-30588] Fix clearSavedViewerState

API.md, android/src/main/java/com/pdftron/reactnative/utils/Constants.java, android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/DocumentViewController/RNTPTDocumentViewController.h, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, lib/src/DocumentView/DocumentView.js, package.json, src/DocumentView/DocumentView.tsx
https://linear.app/pdftron/issue/CPM-23/[support-31669]-override-share-button-behavior
=> Override toolbar button press CPM-23

README.md, package.json
https://linear.app/pdftron/issue/CPM-24/[support-31589]-yarn-installation-issues
=> Installation error CPM-24

API.md, android/src/main/java/com/pdftron/reactnative/utils/Constants.java, android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, lib/src/DocumentView/DocumentView.js, package.json, src/DocumentView/DocumentView.tsx
https://linear.app/pdftron/issue/CPM-31/[support-6006]-community-add-a-ontoolbarchange-event-for-when-the
=> Current toolbar changed event listener (CPM-31)

ios/RNTPTDocumentView.h, ios/RNTPTDocumentView.m, ios/RNTPTDocumentViewManager.m, package.json
add iOS API support for setting document cache path as `openURLCachePath`
=> React Native API to set document cache path

ios/RNTPTDocumentView.m, package.json
datetext tool fix in RNTPTDocumentView.m
=> Fix key mapping for dateText Tool

API.md, package.json, src/DocumentView/DocumentView.tsx
update to explicitly include actions modify, delete, add, undo, redo
also update API.md documentation to include undo, redo event
=> Update onExportAnnotationCommand prop

android/src/main/java/com/pdftron/reactnative/views/DocumentView.java, package.json
support for free text date when trying to add to custom toolbar
=> Android API Support for date text annotation support

android/build.gradle, package.json
Fixes:
- Issue with whole word text search
- Issue with signature crash on >10MB selected file
=> Update to stable nightly 9.5.1-beta01

android/build.gradle, package.json
=> [Android] Update kotlin to 1.6.20

android/build.gradle, package.json
Also update lifecycle lib to match Apryse SDK version
=> [Android] Update to 10.7.0
