ApryseSDK/pdftron-react-native

- package.json
When I run a project with PDFTron on IOS with `yarn`, the follow error appears on pod
```
[!] The `RNPdftron` pod failed to validate due to 1 error:
- ERROR | attributes: Missing required attribute `summary`.
```
Just add a description on `package.json` fix the problem
> UPDATE - description on package.json

- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
Was having some issues with the latest version.
When leaving the PDFTron screen our app was crashing with this error:
```	
20:32:52.393	unknown:ReactNative	Exception in native call
java.lang.NullPointerException: Attempt to invoke virtual method 'com.pdftron.pdf.controls.PdfViewCtrlTabFragment com.pdftron.pdf.controls.PdfViewCtrlTabHostFragment.getCurrentPdfViewCtrlFragment()' on a null object reference
at com.pdftron.reactnative.views.DocumentView.getPdfViewCtrl(DocumentView.java:539)
at com.pdftron.reactnative.views.DocumentView.onDetachedFromWindow(DocumentView.java:329)
at android.view.View.dispatchDetachedFromWindow(View.java:14561)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3071)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
at …
```
> Fix: Attempt to invoke method on null object

- ios/RNTPTDocumentView.m
The "fitMode" property was not updating the view on iOS so I had to set de "SetPageRefViewMode" as well in the native code.
This way the view opened as I had set in the "fitMode" property.
I don't know if it's the best implementations, fell free to do any changes on the code.
Tested on iPhones: 6, 6 Plus, 5c and iPad mini.
> Fix for iOS FitMode

- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.m
- src/Config/Config.js
Add a constant for the pan tool and handling for both Android and iOS.
For some reason the pan tool is not included in the current set of supported tools. This change simply adds the pan tool.
> Add support for Pan tool to setToolMode

- ios/RNTPTDocumentView.m
Add missing iOS functionality to disable the measurement tools and the callout tool.
> Allow measurement annotation tools and the callout tool to be disabled

- README.md
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- ios/RNTPTDocumentViewManager.m
- src/DocumentView/DocumentView.js
Allows setting whether or not a stylus (e.g. Apple Pencil on iOS) starts drawing ink annotations when in Pan mode.
Default is false on Android, true on iOS.
> Add useStylusAsPen prop

- README.md
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- ios/RNTPTDocumentViewManager.m
Add `longPressMenuEnabled` BOOL to determine whether or not to show the long press menu.
Default is `true`.
> Long press menu enabled prop

- ios/RNTPTDocumentView.m
- package.json
iOS `Edit Text` string was recently changed to `Edit`.
Updating the wrapper to match.
> iOS Edit Text Fix

- README.md
- android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- ios/RNTPTDocumentViewManager.h
- ios/RNTPTDocumentViewManager.m
- ios/RNTPTDocumentViewModule.m
- src/DocumentView/DocumentView.js
Rename 3 functions:
- setValueForFields -> setValuesForFields
- setFlagForAnnotations -> setFlagsForAnnotations
- setPropertyForAnnotation -> setPropertiesForAnnotation
update both Android and iOS, bridge implementations in js (an add notes to old functions), and update README
UPDATE:
For iOS, also do some fixes:
- update importAnnotation
- update the handling of thumbnailViewEditingEnabled
> function rename and iOS fix

- API.md
- android/src/main/java/com/pdftron/reactnative/utils/Constants.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- ios/RNTPTDocumentViewManager.m
- package.json
- src/Config/Config.js
sticky-note pop-up could be disabled by overrideBehavior. It would call onBehaviorActivated if selected.
Annotation type is now added as part of the promise result for onAnnotationsSelected, onAnnotationChanged and onQuickMenuButtonPressed.
> enable sticky-note pop-up toggling + annotation type

- API.md
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
Add support for customizing bottom toolbar on Android. Currently only the outline list, thumbnail list, share, view mode, search, and reflow buttons are supported
Example:
`          bottomToolbar={[Config.Buttons.reflowButton, Config.Buttons.listsButton, Config.Buttons.thumbnailsButton, Config.Buttons.shareButton, Config.Buttons.viewControlsButton,  Config.Buttons.searchButton]}
`
> Support custom bottom toolbar for Android

- API.md
- README.md
Fixing small typos, formatting issues, and wrong examples or inconsistencies with the website documentation.
> Update minor documentation inconsistencies with website

- API.md
- android/src/main/java/com/pdftron/reactnative/utils/Constants.java
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- ios/RNTPTDocumentViewManager.m
- src/Config/Config.js
- src/DocumentView/DocumentView.js
Implemented exposure of:
- imageInReflowEnabled (Android) and PTReflowViewController.reflowMode (iOS)
- reflowOrientation (Android) 
For each property in RN, I used the Android name.
Removed my exposures of:
- annotationsListEditingEnabled (Android) and PTAnnotationViewController.readonly (iOS)
- PTReflowViewController.scrollingDirection (iOS)
> Expose native UI customization apis

- API.md
- ios/RNTPTDocumentView.m
- package.json
Due to refactoring in the PTAnnotationViewController class, the annotationListEditingEnabled prop no longer works on iOS. 
Until a solution is made, the prop should be set to as Android only.
> Set annotationListEditingEnabled as Android only

- API.md
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- ios/RNTPTDocumentViewManager.m
- package.json
- src/DocumentView/DocumentView.js
Added new parameter `annotations` to `onExportAnnotationCommand`. `annotations` is an array of changed annots with the following data:
- id
- page number (non-collab mode only)
- type (non-collab mode only)
> Add annotation id to onExportAnnotationCommand

- API.md
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
- Added two new properties exportPath and openUrlPath for Android
- Removed mCacheDir from Document.java and replaced it with mExportPath and mOpenUrlPath, these default to the cached Directory
- Updated API.md with information on the two new properties
> [Support] Android exportPath & openUrlPath

- ios/RNTPTDocumentView.m
- package.json
When document view controller scrolls or finishes zoom, check that the delegate responds to the correct method it's about to call.
> (iOS) fix delegate respondsToSelector check

- android/build.gradle
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
- Added showConversionDialog(false) to setup function in DocumentView
- Updated PDFTron dependencies to - com.pdftron:pdftron:9.0.2-beta10
- Updated Library version
> [Support] Android hide conversion progress dialog

- API.md
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- ios/RNTPTDocumentViewManager.m
- package.json
- src/DocumentView/DocumentView.js
Exposed the following APIs:
- photoPickerEnabled (Android only; whether to show the option to pick images in the signature dialog)
- autoResizeFreeTextEnabled (iOS and Android)
> autoResizeFreeTextEnabled, photoPickerEnabled for signatures

- android/src/main/java/com/pdftron/reactnative/utils/Constants.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
- src/Config/Config.js
Add option to disable DigitalSignature in overflow menu
https://support.pdftron.com/a/tickets/23262
- add a new config (digitalSignatureButton) to disable digital signature in overflow menu
> Add option to disable DigitalSignature in overflow menu

- API.md
- android/build.gradle
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
- src/DocumentView/DocumentView.js
Add openSavedCopyInNewTab prop
https://support.pdftron.com/a/tickets/23200
- add a new prop (openSavedCopyInNewTab) to not open the saved file in a new tab
> [Support] Add openSavedCopyInNewTab prop

- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
Support Ticket:
https://support.pdftron.com/a/tickets/23214
Do array size check when publishing event so we don't over send non-necessary events
> [Droid] Issue SDK Support 23214, dont send event on empty array

- API.md
- android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- ios/RNTPTDocumentViewManager.h
- ios/RNTPTDocumentViewManager.m
- ios/RNTPTDocumentViewModule.m
- package.json
- src/DocumentView/DocumentView.js
Exposed `openThumbnailsView` on iOS and Android.
This method opens a page thumbnails view that allows user to navigate and manipulate document pages.
> openThumbnailsView

- API.md
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- ios/RNTPTDocumentViewManager.m
- package.json
- src/DocumentView/DocumentView.js
Exposed `disableEditingByAnnotationType` prop for iOS and Android. This prop takes [Config.Tool](https://github.com/PDFTron/pdftron-react-native/blob/test-add-an-api/src/Config/Config.js) constants and defines annotation types that cannot be edited after creation.
> Expose disableEditingByAnnotationType

- API.md
- ios/RNTPTDocumentView.m
- package.json
Comment out call to native API `excludedAnnotationTypes` which will be in future version.
> Comment out excludedAnnotationTypes

- API.md
Changed the type description from `string` to the appropriate`Conifg.js` constant
> Updated typings of props that use Config.js constants

- API.md
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.m
- package.json
Refactored the iOS implementation to return an object containing the field's name, type and value (of any type). 
On Android, an unnecessary line of code was removed.
> Updated onFormFieldValueChanged

- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
In Android `getAnnotationsData` method, replaced `WritableMap.copy` with `WritableMap.merge` (`copy` doesn't exist in RN 0.60.0).
> (Android) getAnnotationsData WritableMap fix

- API.md
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- package.json
- src/DocumentView/DocumentView.js
Some iOS methods returned a `rect` value while the Android counterparts returned `screenRect` and `pageRect`. This update makes the iOS methods consistent with the Android ones by replacing `rect` with `screenRect` and `pageRect`. 
This update affects the following methods:
- `getAnnotationAtPoint`
- `getAnnotationListAt`
- `getAnnotationsOnPage`
- `onAnnotationMenuPress`
- `onAnnotationsSelected`
- `onBehaviorActivated`
This update also fixes a few unrelated typos or wordings in `API.md`.
> (iOS) Replace rect with screenRect, pageRect

- API.md
- android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
- src/DocumentView/DocumentView.js
Exposed `showRotate` method. Android only.
This method opens a rotate dialog which allows user to rotate pages of the document.
> showRotate

- API.md
- android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
- src/DocumentView/DocumentView.js
Exposed Android `getSavedSignatureJpgFolder` which retrieves the absolute file path to the folder containing the saved signature JPGs.
> (support, Android) expose getSavedSignatureJpgFolder

- API.md
- ios/RNTPTDocumentView.m
- package.json
Previously, some APIs were only available in nightlies. Due to the latest iOS release they are now available. 
This PR:
- removes two iOS podspec nightly mentions from API.md.
- uncomments a call to a native API which is now available.
> (iOS) Remove old podspec nightly mentions

- API.md
In the table describing the modes associated with `annotationManagerEditMode` and `annotationManagerUndoMode`, `Config.AnnotationManagerEditMode.Others` was used instead of `Config.AnnotationManagerEditMode.All` and `Config.AnnotationManagerUndoMode.Others` was used instead of `Config.AnnotationManagerUndoMode.All`.
> Fixed typo in the annotation manager mode props

- API.md
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
After a discussion with Shirley, we realised that `pageStackEnabled` and `showQuickNavigationButton` were doing the same thing on Android but the latter was a worse implementation. 
Since, latter was working properly on iOS, we decided to copy over former's implementation and then deprecate `pageStackEnabled`.
> (Android) Updated `showQuickNavigationButton`

- API.md
- ios/RNTPTDocumentView.m
This PR:
- uncomments `annotationsListEditingEnabled` call since it is available now
- initialises value to true
> (iOS) Update annotationsListEditingEnabled

- ios/RNTPTDocumentView.m
- package.json
While working on the annotation manager modes for Flutter, David and I noticed an issue in the React Native implementation. This PR fixes that probem.
> (iOS) Updated implementation of `annotationManagerEditMode`

- android/src/main/java/com/pdftron/reactnative/utils/Constants.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- lib/src/Config/Config.js
- package.json
- src/Config/Config.ts
* (iOS) Added support to disable `insertPages` button using either `disabledTools` or `disabledElements`.
* (iOS) Disable `insertPages` button when disabling `editPages` button.
* (Android) Add support for the `Config.Tools.insertPage` and `Config.Buttons.insertPageButton` constants in `disabledTools` and `disabledElements`
> (Support) Disable Insert Pages Button

- android/src/main/java/com/pdftron/reactnative/utils/Constants.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- lib/src/Config/Config.js
- package.json
- src/Config/Config.ts
Equivalent of https://github.com/PDFTron/pdftron-flutter/pull/182
STR:
annotationMenuItems={[Config.AnnotationMenu.delete]}
master: when using multi-select, the menu is not just delete, should be just delete
> [Android] Fix incorrect logic in annot menu for multi-select tool

- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
Call the following custom toolbar (note empty toolbar name)
const myToolbar = {
[Config.CustomToolbarKey.Id]: 'myToolbar',
[Config.CustomToolbarKey.Name]: '',
[Config.CustomToolbarKey.Icon]: Config.ToolbarIcons.Annotate,
[Config.CustomToolbarKey.Items]: [Config.Tools.annotationCreateTextHighlight,
Config.Tools.annotationCreateFreeHighlighter,
Config.Tools.annotationCreateFreeText,
Config.Tools.annotationEraserTool,
Config.Buttons.undo,
Config.Buttons.redo
]
};
...
annotationToolbars={[myToolbar]}
The custom toolbar will not be used. If the toolbar title is non empty, then it will work.
This PR fixes this issue to allow for empty toolbar names.
> [Android] Fix issue where empty custom toolbar title can not be used

- ios/RNTPTDocumentView.m
- package.json
- also allow fallback to SF Symbols
> Fix image variable name for custom tool items on iOS

- .github/workflows/npm_publish.yml
the conditional statement prevents the first job from being executed, and since the second job depends on the first job it will be skipped since the first job failed to execute
> fix for forked repos

- ios/RNTPTDocumentView.m
* When you set initialPageNumber prop in React-Native the iOS app does not set the page number in the document that is loaded
* changed the location of check for initialPageNumber prop value check
> fixing initial Page number bug

- API.md
- android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java
- android/src/main/java/com/pdftron/reactnative/nativeviews/RNPdfViewCtrlTabHostFragment.java
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- ios/RNTPTDocumentViewManager.h
- ios/RNTPTDocumentViewManager.m
- ios/RNTPTDocumentViewModule.m
- lib/src/DocumentView/DocumentView.js
- package.json
- src/DocumentView/DocumentView.tsx
https://linear.app/pdftron/issue/CPM-4/[support-30534]-method-api-to-enabledisable-annotation-toolbar-item
Some issues noticed on the native side.
Android: 
The toolbar buttons are being disabled using the `AnnotationToolbarComponent setItemEnabled` [method](https://www.pdftron.com/api/android/javadoc/reference/com/pdftron/pdf/widget/toolbar/component/AnnotationToolbarComponent.html#setItemEnabled(int,%20boolean)), but while the buttons appear disabled as they are greyed out the user is still able to click on the button and use its functionality.
iOS:
The buttons are being disabled by setting the `enabled` property of the `UIBarButtonItem` to false. Doing so properly disables the buttons as they don't receive events, but the appearance of the button remains the same as when they are …
> Enable/disable annotation toolbar item CPM-4

- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
Fixes case where users were editing documents when in Read Only mode and setting to reading mode in Android RN app
Closes NSDK-202
Steps to reproduce:
1. in apps.js, set readOnly to true
2. open app
3. open viewing mode menu and set to reading mode from single page
4. highlight over text in document to see pop up menu
5. should see no text annotation edits (strikethrough, outline, highlight, etc.)
> [Support-33786 | Android] Read only mode Android React Native fix

- android/src/main/java/com/pdftron/reactnative/modules/RNPdftronModule.java
- package.json
Added setOpenUrlPageStateAsyncCache to clearSavedViewerState
Closes NSDK-190
> [Support-32057] ClearSavedViewerState method not working with XOD files

- ios/RNTPTDocumentView.m
- package.json
Closes [NSDK-226](https://linear.app/pdftron/issue/NSDK-226/[support-34290]-add-readonly-config-for-ios-in-react-native)
Fixed issue where users were still able to add annotations in Reader mode when viewer was in read-only
STR:
1. In `App.js`, set `readOnly={true}`
2. Enter Reading Mode
3. Long press on text to bring up context
4. Should not have any options to add annotations (highlight, strikethrough, etc.)
> [Support-34290] Disable annotating on Reader Mode when read-only (iOS)

- API.md
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- ios/RNTPTDocumentViewManager.m
- lib/src/DocumentView/DocumentView.js
- package.json
- src/DocumentView/DocumentView.tsx
Closes [NSDK-237](https://linear.app/pdftron/issue/NSDK-237/[support-29040]-add-api-to-set-signature-colours-react-native)
Adds API that allows users to specify a list of colors that the user can select when creating a signature.
Testing:
1. In `App.js`, set the `signatureColors` prop. For example: 
```js
<DocumentView
...
signatureColors={[
{ 'red': 255, 'green': 0, 'blue': 0 },
{ 'red':   0, 'green': 0, 'blue': 0 },
]}
/>
```
2. Open signature creation dialog. Should only display specified colors
> [Support-29040] Set signature colors

- API.md
- android/src/main/java/com/pdftron/reactnative/utils/Constants.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- lib/src/Config/Config.js
- package.json
- src/Config/Config.ts
Closes [NSDK-201](https://linear.app/pdftron/issue/NSDK-201/[support-33786]-add-api-to-disable-reading-mode-settings-button)
Adds the Reader Mode Settings button in `Config.ViewModePickerItem` so users can hide the button using the `hideViewModeItems` prop
Testing:
1. In `App.js`, set the `hideViewModeItems` prop:
```js
<DocumentView
...
hideViewModeItems={[
Config.ViewModePickerItem.ReaderModeSettings,
]}
/>
```
2. Run the app and change view mode to reader mode. Should not be able to see the reader mode settings button
> [Support-33786] Add API to disable Reading Mode Settings button

- android/src/main/java/com/pdftron/reactnative/utils/Constants.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- lib/src/Config/Config.js
- package.json
- src/Config/Config.ts
added support to disable count measurement tool on iOS/Android
`disabledTools={[Config.Tools.annotationCreateLine, Config.Tools.annotationCreateRectangle, Config.Tools.annotationCountTool]}`
> Add API support for disabling count tool

- android/build.gradle
- package.json
to fix crashing on changing annotation to view/vice-versa that adjusts the annotation tools toolbar
> Update react-native project to use SDK version 9.3.2beta-05 snapshot

- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- lib/src/Config/Config.js
- package.json
- src/Config/Config.ts
added iOS api support for date text for onToolChanged API to read AnnotationCreateFreeTextDate instead of 'unknown tool'
android
> API Support for DateText annotation/tool type

- ios/RNTPTDocumentView.m
- package.json
force UI elements, not pdfviewctrl object for forceAppThemeProp
> Fix forceAppTheme on iOS for UI Elements, not pdfviewctrl document

- android/build.gradle
- android/src/main/java/com/pdftron/reactnative/modules/DocumentViewModule.java
- android/src/main/java/com/pdftron/reactnative/utils/DocumentViewUtils.kt
- android/src/main/java/com/pdftron/reactnative/viewmanagers/DocumentViewViewManager.java
- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- example/App.js
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- ios/RNTPTDocumentViewManager.h
- ios/RNTPTDocumentViewManager.m
- ios/RNTPTDocumentViewModule.m
- lib/src/DocumentView/DocumentView.js
- package-lock.json
- package.json
- src/DocumentView/DocumentView.tsx
To test:
Open doc with existing stamp annotation in respective platforms (iOS/Android have different paths to get docs)
in app.js override button:
replace annotationId in snippet with annotation id from doc
```
try {
await this._viewer.setStampImageData(
annotationId = 'a3302f72-bfef-664c-b2d3-28055684b483', 
pageNumber = 1, 
stampImageDataUrl = 'https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png'
)
} catch (e) {
console.error(e)
}
```
> API Support for setting stamp image programmatically given URL

- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
Annotation selected should now be AnnotationCreateFreeTextDate
> [Support-35444] Fix issue for DateText annotation type being selected as AnnotationCreateFreeText

- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- ios/RNTPTDocumentView.m
- package.json
Different annotation form field types should now should their respective form field annotations
tested with this app.js:
```
/**
* Sample React Native App
* https://github.com/facebook/react-native
*
* @format
* @flow strict-local
*/
import React, {useRef} from 'react';
import {Alert, BackHandler, PermissionsAndroid, Platform} from 'react-native';
import {DocumentView, RNPdftron} from 'react-native-pdftron';
const App = () => {
const viewer = useRef(null);
React.useEffect(() => {
RNPdftron.initialize('');
RNPdftron.enableJavaScript(true);
}, []);
React.useEffect(() => {
if (Platform.OS === 'android') {
requestStoragePermission();
}
}, []);
const requestStoragePermission = async () => {
try {
const granted = await PermissionsAndroid.request( …
```
> Added different annotation types for Form Field Annotation types 

- ios/RNTPTDocumentView.m
- package.json
fixed issue to force button to top app nav bar right bar if toolbar button is found in other app bar when using prop in app.js config
```
topAppNavBarRightBar={[
Config.Buttons.searchButton,
Config.Buttons.thumbnailsButton,
Config.Buttons.viewControlsButton,
]}
```
also refactored ensureUniqueBottomBarButtonItem to use 3 functions instead of the 1 for specificity:
- removeToolbarButtonItem
- removeLeftBarButtonItem
- removeRightBarButtonItem
on iOS16.2 iPad (Simulator):
(before)
(after)
> topAppBarNavRightBar checks if button exists in other navigation bar/UI bars 

- .github/workflows/jsBuilder.yml
- package.json
- Revert merge master, instead just checkout
- Upon further investigation, it seems that the `-m` tag did nothing, so we can just take it out.
> Fix package version update script again

- android/build.gradle
- package.json
Any mention of android-kotlin-extensions library is removed
was deprecated as of this error:
> The Android extensions ('kotlin-android-extensions') compiler plugin is no longer supported. Please use kotlin parcelize and view binding. More information: https://goo.gle/kotlin-android-extensions-deprecation
> Remove Android-Kotlin-Extensions library

- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- lib/src/Config/Config.js
- package.json
- src/Config/Config.ts
android only implementation
test by adding `Config.Tools.annotationCreateRectAreaMeasurement` to any of the document view props like disabledTools, etc.
> Add rect area measurement as android only tool

- android/src/main/java/com/pdftron/reactnative/views/DocumentView.java
- package.json
- Fragment transaction only when activity is started
- Component valid check for PDFViewCtrl and ToolManager on document loaded
Diff with base:
> [Android] Potential fix for lifecycle issue

- API.md
- ios/RNTPTDocumentView.h
- ios/RNTPTDocumentView.m
- ios/RNTPTDocumentViewManager.m
- package.json
- Add `replace` parameter for iOS implementation of `importAnnotations`
- No longer uses the `PTAnnotationManager` to import the XFDF string
closes REASDK-61
> [iOS] Match Android implementation of `importAnnotations`

- src/DocumentView/DocumentView.tsx
If the promise isn't returned the host project can't handle the case of it being rejected.
> Return promise

- android/build.gradle
- package.json
Resolves the following warning when using React Native `0.73` and above
```
WARNING: The specified Android SDK Build Tools version (30.0.2) is ignored, as it is below the minimum supported version (34.0.0) for Android Gradle Plugin 8.2.1.
```
> Use root project build tools version if present

- ios/RNTPTDocumentView.m
- package.json
Addresses an issue with a rotated image stamp that has called setStampImageData's which ended up unrotating an image that wasn't supposed to be rotated
> [iOS] Fix setStampImageData unrotating image annotations
